export type RemaxListing = {
  totalPages: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
  isValid: boolean;
  errorMessage: null;
  total: number;
  page: number;
  pageSize: number;
  results: RemaxResultsItem[];
  elapsedMilliseconds: null;
  facets: unknown;
  geoPoints: null;
  globalCentroid: null;
};
export type RemaxResultsItem = {
  previousPrice: null;
  previousPriceText: string;
  priceReductionPercentage: null;
  languageCode: string;
  smallDescription: string;
  bigDescription: string;
  descriptions: DescriptionsItem[] | null;
  contractNumber: string | null;
  listingStatus: string;
  listingCurrencyCode: string;
  landRegister: string;
  businessType: string;
  listingType: string;
  listingCategory: string | null;
  conservationStatus: null | string;
  marketStatus: string;
  garageType: string | null;
  listingSightType: null | string;
  locationType: null;
  floor: null;
  floorDescription: string | null;
  country: string;
  tipology: null;
  energyEfficiencyLevel: string;
  emissionEfficiencyLevel: null;
  listingClass: string;
  neighborhood: null;
  campaign: Campaign;
  listingMapPictureUrl: string;
  listingMapPictureAltUrl: string;
  listingPictureUrl: string;
  listingImageAlt: string;
  listingAttributes: ListingAttributesItem[];
  listingRooms: ListingRoomsItem[];
  specialLabel: string;
  soldLabel: string;
  cellPhoneEncoded: string;
  phoneNumberEncoded: string;
  nearRegions: NearRegionsItem[];
  hasVTour: boolean;
  hasVideo: boolean;
  isActive: boolean;
  translations: null | Translations;
  modified: string;
  rentalPriceGranularityText: null;
  previousListingTitle: null;
  legalComponentText: null;
  totalAreaDisplay: string | null;
  livingAreaDisplay: string | null;
  lotSizeDisplay: null | string;
  builtAreaDisplay: null | string;
  legalEnergyEstimatedCostText: null;
  legalEnergyLevelText: null;
  energyEfficiencyImageUrl: string;
  emissionEfficiencyImageUrl: null;
  newListingTitle: null;
  userName: string;
  userPictureURL: string;
  userPicture: null;
  userEmail: null;
  userCellPhone: string;
  userCellPhoneTrimmed: string;
  userPublicName: string;
  userTeamName: null | string;
  userShortLink: string;
  cellPhoneNetworkCallTypeDescription: string;
  phoneNumberNetworkCallTypeDescription: string;
  userAgencyName: null;
  userAgencyAddress: null;
  userAgencyZipCode: string;
  userAgencyEnterpriseName: null;
  userAgencyLicenseNumber: null;
  userAgencyPhoneNumber: string;
  userAgencyOfficeURL: null;
  officeAddress: null;
  officeName: string;
  officePublicName: string;
  customDisplayTitle: string;
  withMaxFinanceConnection: boolean;
  isExclusive: boolean;
  containsCountryCode: boolean;
  licenseNumberInfo: null;
  isExactAddress: boolean;
  floorID: number | null;
  entity: string;
  masterID: number;
  languageID: number;
  id: number;
  officeID: number;
  officeNumber: string;
  userID: number;
  agentID: number;
  listingStatusID: number;
  isOnline: boolean;
  marketDays: number;
  tipologyID: null;
  listingClassID: number;
  businessTypeID: number;
  listingCategoryID: number | null;
  conservationStatusID: null | number;
  contractDate: string;
  constructionYear: number | null;
  pricePerSqM: null;
  marketStatusID: number;
  garageTypeID: number | null;
  locationTypeID: null;
  isRemaxCollection: boolean;
  isSpecialExclusive: boolean;
  energyEfficiencyLevelID: number;
  emissionEfficiencyLevelID: null;
  efficiencyOrder: number;
  publicAddress: boolean;
  privatePrice: boolean;
  publishDate: string;
  soldDate: null;
  floorAsNumber: number | null;
  garageSpots: number;
  hasMultimedia: boolean;
  hasCampaign: boolean;
  isOpportunity: boolean;
  isMultipleProposal: boolean;
  isBankAppraisalIncluded: boolean;
  dreamHouseProject: boolean;
  zipCode: string;
  localZone: string;
  address: string;
  countryID: number;
  region1ID: number;
  regionSearch2: string;
  regionSearch3: string;
  regionSearch4: null | string;
  region4ID: null | number;
  regionName4: null | string;
  doorNumber: string | null;
  apartmentNumber: null | string;
  parking: boolean;
  garage: boolean;
  elevator: boolean | null;
  electricCarsCharging: boolean;
  accessibleLeasing: boolean;
  totalRooms: null | number;
  numberOfBedrooms: number | null;
  numberOfWC: number;
  numberOfBathrooms: number;
  totalArea: number | null;
  livingArea: number | null;
  lotSize: null | number;
  builtArea: null | number;
  listingAttributesIds: number[];
  listingVideos: string[];
  vTourLink: string;
  buildingDevelopmentID: null | number;
  buildingDevelopmentName: null;
  buildingDevelopmentNameEncoded: string;
  mls: boolean;
  mlsBank: null;
  mlsReference: null;
  priceReductionPercentageValue: null;
  teamID: null | number;
  whatsAppChatLink: null;
  listingTitle: string;
  autocompleteListingTitle: string;
  isSold: boolean;
  coordinates: Coordinates;
  longitude: number;
  latitude: number;
  listingPrice: number;
  listingPriceText: string;
  listingTypeID: number;
  isSpecial: boolean;
  listingPictures: string[];
  regionName1: string;
  region2ID: number;
  regionName2: string;
  region3ID: number;
  regionName3: string;
  listingMetatagTitle: string;
  listingMetatagDescription: string;
  descriptionTags: string;
};
export type DescriptionsItem = {
  languageCode: string;
  languageID: number;
  description: string;
};
export type Campaign = {
  campaignName: null;
  campaignValue: null;
  startDate: string;
  endDate: null;
  hasCampaign: boolean;
  bankAppraisalLabel: null;
};
export type ListingRoomsItem = {
  id: number;
  listingID: number;
  roomDimensions: null | string;
  roomSize: null | string;
  roomType: string;
  roomTypeID: number;
  roomDescription: null | string;
};
export type NearRegionsItem = {
  regionID: number;
  regionName: string;
  regionSearch: string;
};
export type Coordinates = {
  latitude: number;
  longitude: number;
};
export type Translations = {
  BuyMetatagDescription: string;
  Email: string;
  Monthly: string;
  ContactCustomMessage: string;
  ListingDetails: string;
  Name: string;
  SendMessageLabel: string;
  EnergyEfficiency: string;
  SectionCreditSimulation: string;
  CopyURL: string;
  SectionDescription: string;
  FormInvalidRequiredCheckbox: string;
  RentCustomDisplayTitle: string;
  RentCustomDisplayTitleCollection: string;
  SendMessage: string;
  Agent: string;
  ConstructionYear: string;
  EmissionEfficiency: string;
  GarageSpot: string;
  SectionEnergyDetails: string;
  FormInvalidName: string;
  LegalRequirementTitle: string;
  BuyMetatagTitleCollection: string;
  GDPRText: string;
  WCs: string;
  RentMetatagDescriptionCollection: string;
  VirtualTour: string;
  EmailAddress: string;
  ContactAgent: string;
  FormInvalidEmail: string;
  ElectricCarsCharging: string;
  MarketDays: string;
  SectionDetails: string;
  AgentDetailsRoute: string;
  Details: string;
  FormInvalidMessage: string;
  Bedrooms: string;
  BuiltArea: string;
  Message: string;
  Yes: string;
  FormInvalidPhone: string;
  RentMetatagDescription: string;
  SeeMobilePhone: string;
  TotalArea: string;
  BuyCustomDisplayTitle: string;
  RoomArea: string;
  Elevator: string;
  SeePhoneNumber: string;
  TotalLotSize: string;
  BuyMetatagDescriptionCollection: string;
  Call: string;
  Floor: string;
  LivingArea: string;
  No: string;
  Return: string;
  DevelopmentRoute: string;
  SectionMap: string;
  "3dView": string;
  DescriptionKnowMore: string;
  NearbyParishes: string;
  Parking: string;
  SectionRooms: string;
  RentMetatagTitleCollection: string;
  RoomDimensions: string;
  BuyCustomDisplayTitleCollection: string;
  Contact: string;
  Rooms: string;
  RentMetatagTitle: string;
  ContactedByMaxFinance: string;
  SectionNearbyRegions: string;
  Total: string;
  Summary: string;
  Exclusivity: string;
  BuyMetatagTitle: string;
  SectionAttributes: string;
  SectionContactAgent: string;
};
export type ListingAttributesItem = {
  id: number;
  description: string;
};
